version: 2

jobs:
  fmt:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Check formating
          command: terraform fmt --recursive -check=true

  validate:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: terraform init
      - run:
          name: Validate files
          command: terraform validate

  terratest:
    docker:
      - image: web3f/terratest:v0.1.0
    steps:
      - checkout
      - run:
          description: Integration tests
          command: |
            cd test
            go test -v -timeout 30m

workflows:
  version: 2
  test-module:
    jobs:
      - fmt
      - validate
      - terratest:
          requires:
            - fmt
            - validate

